# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a46b3f3cacf32fd39f48d61983c75f70c481e5e919f35e8317810e38ebf07f797bfbd10223842a4d861e3c29d4c6228ca2f1d15379bc487664b413bc1df52349

test:
  secret_key_base: 5ffd4af371e63d5049bc90bea6cc66beb2240477b7580ad7370b5a7616733b94378062749388af41197b952037b0b85f9a90fb4f9a85356a0e602c1d20dc0fbb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
